### ISSUE TITLE
month constant list

### ISSUE THREAD

**Issue by GraceDmello** [ajaymathur/fun-community#2]
Can get it from moment

moment.months()

["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

**Comment by ajaymathur** [comment]
hjvj

**Comment by GraceDmello** [comment]
https://jsfiddle.net/dstorey/Xgerq/

**Comment by ajaymathur** [comment]
We are not storing date in valid moment format. It may be overkill at the moment as we are just displaying birthdays, if in future any enhancement in taken up on birthday tab then this change can come with it.
