### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by pragyaPS** [ajaymathur/fun-community#7]
Someone has become pro in ES6 
dataSource: new ListView.DataSource({
        rowHasChanged: (row1, row2) => row1 !== row2,
      })  this one is impressive

and you don't need to bind your function inside class constructor like this 
   this.renderListData = this.renderListData.bind(this);

**Comment by ajaymathur** [comment]
If we are calling function from html in render then it is required else not, this is just safeguard here. will re factor code .
